// Package fixproposals implements structured fix proposals (spec §15,
// §6.9): a candidate patch — generated by a routed AI provider or
// authored manually — that can be reviewed, applied to a disposable
// temporary workspace, and only written to the real repository after
// explicit approval (spec §3.3 "It must not apply patches" for the AI
// itself; only an approved human action ever writes to the repository).
//
// Patches are parsed and applied by a small pure-Go unified-diff engine
// rather than shelling out to `git apply`/`patch` — consistent with the
// project's established preference for parsing over subprocess
// invocation (spec §23.3, already applied to Compose file parsing), and
// it avoids introducing a new command-execution surface for a diff body
// that may originate from an AI provider or a malicious project.
package fixproposals

import (
	"bufio"
	"fmt"
	"strconv"
	"strings"
)

// LineKind identifies one line within a diff hunk.
type LineKind int

const (
	LineContext LineKind = iota
	LineAdd
	LineRemove
)

// DiffLine is one line of a hunk body.
type DiffLine struct {
	Kind LineKind
	Text string
}

// Hunk is one @@ ... @@ block.
type Hunk struct {
	OldStart int
	OldLines int
	NewStart int
	NewLines int
	Lines    []DiffLine
}

// FileChange is the parsed diff for a single file.
type FileChange struct {
	OldPath   string
	NewPath   string
	IsNew     bool
	IsDeleted bool
	Hunks     []Hunk
}

// Path is the file's path in the resulting tree (NewPath, or OldPath for
// a deletion).
func (fc FileChange) Path() string {
	if fc.IsDeleted {
		return fc.OldPath
	}
	return fc.NewPath
}

// ErrMalformedDiff is returned for a unified diff this parser can't make
// sense of. The caller must never guess at a malformed diff's intent.
var ErrMalformedDiff = fmt.Errorf("fixproposals: malformed unified diff")

// ParseUnifiedDiff parses a standard unified diff (as produced by `git
// diff` / `diff -u`) into per-file changes. It supports the subset
// needed for typical small patches: `---`/`+++` file headers, `@@
// -l,s +l,s @@` hunk headers (count defaulting to 1 when omitted), and
// context/add/remove lines. "\ No newline at end of file" marker lines
// are recognized and skipped (trailing-newline fidelity is
// best-effort, not byte-exact).
func ParseUnifiedDiff(diff string) ([]FileChange, error) {
	var changes []FileChange
	var current *FileChange
	var hunk *Hunk

	flushHunk := func() {
		if hunk != nil && current != nil {
			current.Hunks = append(current.Hunks, *hunk)
			hunk = nil
		}
	}
	flushFile := func() {
		flushHunk()
		if current != nil {
			changes = append(changes, *current)
			current = nil
		}
	}

	scanner := bufio.NewScanner(strings.NewReader(diff))
	scanner.Buffer(make([]byte, 0, 64*1024), 10*1024*1024)
	for scanner.Scan() {
		line := scanner.Text()

		switch {
		case strings.HasPrefix(line, "--- "):
			flushFile()
			current = &FileChange{}
			current.OldPath = normalizeDiffPath(strings.TrimPrefix(line, "--- "))
			if current.OldPath == "" {
				current.IsNew = true
			}

		case strings.HasPrefix(line, "+++ "):
			if current == nil {
				return nil, fmt.Errorf("%w: '+++' header without a preceding '---' header", ErrMalformedDiff)
			}
			current.NewPath = normalizeDiffPath(strings.TrimPrefix(line, "+++ "))
			if current.NewPath == "" {
				current.IsDeleted = true
			}

		case strings.HasPrefix(line, "@@ "):
			if current == nil {
				return nil, fmt.Errorf("%w: hunk header without a file header", ErrMalformedDiff)
			}
			flushHunk()
			h, err := parseHunkHeader(line)
			if err != nil {
				return nil, err
			}
			hunk = &h

		case strings.HasPrefix(line, `\ No newline at end of file`):
			// Trailing-newline fidelity is best-effort; nothing to record.

		case strings.HasPrefix(line, "diff --git ") || strings.HasPrefix(line, "index "):
			// git's extended header lines; ignored, --- / +++ carry the
			// information this parser needs.

		default:
			if hunk == nil {
				if strings.TrimSpace(line) == "" {
					continue
				}
				return nil, fmt.Errorf("%w: unexpected line outside any hunk: %q", ErrMalformedDiff, line)
			}
			if line == "" {
				hunk.Lines = append(hunk.Lines, DiffLine{Kind: LineContext, Text: ""})
				continue
			}
			switch line[0] {
			case '+':
				hunk.Lines = append(hunk.Lines, DiffLine{Kind: LineAdd, Text: line[1:]})
			case '-':
				hunk.Lines = append(hunk.Lines, DiffLine{Kind: LineRemove, Text: line[1:]})
			case ' ':
				hunk.Lines = append(hunk.Lines, DiffLine{Kind: LineContext, Text: line[1:]})
			default:
				return nil, fmt.Errorf("%w: hunk line has no +/-/space prefix: %q", ErrMalformedDiff, line)
			}
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("fixproposals: reading diff: %w", err)
	}
	flushFile()

	if len(changes) == 0 {
		return nil, fmt.Errorf("%w: no file changes found", ErrMalformedDiff)
	}
	return changes, nil
}

func normalizeDiffPath(raw string) string {
	// Strip a trailing tab-separated timestamp some diff tools emit.
	if idx := strings.IndexByte(raw, '\t'); idx != -1 {
		raw = raw[:idx]
	}
	raw = strings.TrimSpace(raw)
	if raw == "/dev/null" {
		return ""
	}
	// git-style a/ and b/ prefixes.
	if strings.HasPrefix(raw, "a/") || strings.HasPrefix(raw, "b/") {
		raw = raw[2:]
	}
	return raw
}

func parseHunkHeader(line string) (Hunk, error) {
	// @@ -oldStart,oldLines +newStart,newLines @@ optional trailing text
	rest := strings.TrimPrefix(line, "@@ ")
	end := strings.Index(rest, " @@")
	if end == -1 {
		return Hunk{}, fmt.Errorf("%w: invalid hunk header: %q", ErrMalformedDiff, line)
	}
	rest = rest[:end]
	parts := strings.Fields(rest)
	if len(parts) != 2 || !strings.HasPrefix(parts[0], "-") || !strings.HasPrefix(parts[1], "+") {
		return Hunk{}, fmt.Errorf("%w: invalid hunk header: %q", ErrMalformedDiff, line)
	}

	oldStart, oldLines, err := parseRange(parts[0][1:])
	if err != nil {
		return Hunk{}, fmt.Errorf("%w: invalid old range in hunk header: %q", ErrMalformedDiff, line)
	}
	newStart, newLines, err := parseRange(parts[1][1:])
	if err != nil {
		return Hunk{}, fmt.Errorf("%w: invalid new range in hunk header: %q", ErrMalformedDiff, line)
	}

	return Hunk{OldStart: oldStart, OldLines: oldLines, NewStart: newStart, NewLines: newLines}, nil
}

func parseRange(s string) (start, count int, err error) {
	if commaIdx := strings.IndexByte(s, ','); commaIdx != -1 {
		start, err = strconv.Atoi(s[:commaIdx])
		if err != nil {
			return 0, 0, err
		}
		count, err = strconv.Atoi(s[commaIdx+1:])
		return start, count, err
	}
	start, err = strconv.Atoi(s)
	return start, 1, err
}
